#!/bin/bash

function overwrite_unity_icon() {
  version=$1
  base_dir="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/Documents/Images/Icons"

  if [ -z "${version}" ]; then
    echo "Please specify Unity version."

    return 1
  fi

  if [ ! -e /Applications/Unity/Hub/Editor/${version}/Unity.app ]; then
    echo "Unity ${version} does not installed in '/Applications/Unity/Hub/Editor/'. Please install Unity ${version} using Unity Hub."

    return 1
  fi

  if [ ! -e $base_dir/Unity.iconset -o ! -f $base_dir/Unity.icns ]; then
    convert_png_to_icns $base_dir/Unity.png $base_dir/Unity
  fi

  cp $base_dir/Unity.png /Applications/Unity/Hub/Editor/${version}/Unity.app/Contents/Resources/LargeUnityIcon.png
  cp $base_dir/Unity.icns /Applications/Unity/Hub/Editor/${version}/Unity.app/Contents/Resources/UnityAppIcon.icns

  sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \; 2>/dev/null
  sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \; 2>/dev/null
  killall Dock
}
