#!/bin/bash

function overwrite_unity_icon() {
  version=$1

  if [ -z "${version}" ]; then
    echo "Please specify Unity version."

    return 1
  fi

  if [ ! -e /Applications/Unity/Hub/Editor/${version}/Unity.app ]; then
    echo "Unity ${version} does not installed in '/Applications/Unity/Hub/Editor/'. Please install Unity ${version} using Unity Hub."

    return 1
  fi

  if [ ! -e $HOME/Documents/Images/Icons/Unity.iconset -o ! -f $HOME/Documents/Images/Icons/Unity.icns ]; then
    convert_png_to_icns $HOME/Documents/Images/Icons/Unity.png $HOME/Documents/Images/Icons/Unity
  fi

   cp $HOME/Documents/Images/Icons/Unity.icns /Applications/Unity/Hub/Editor/${version}/Unity.app/Contents/Resources/UnityAppIcon.icns
}
