#!/bin/bash

function overwrite_unityhub_icon() {
  base_dir="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/Documents/Images/Icons"

  if [ ! -e $base_dir/Unity\ Hub.iconset -o ! -f $base_dir/Unity\ Hub.icns ]; then
      convert_png_to_icns $base_dir/Unity\ Hub.png $base_dir/Unity\ Hub
  fi

  cp $base_dir/Unity\ Hub.icns /Applications/Unity\ Hub.app/Contents/Resources/Unity\ Hub.icns
  sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \; 2>/dev/null
  sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \; 2>/dev/null
  killall Dock
}
