#!/bin/bash

function overwrite_unityhub_icon() {
  if [ ! -e $HOME/Documents/Images/Icons/Unity\ Hub.iconset -o ! -f $HOME/Documents/Images/Icons/Unity\ Hub.icns ]; then
    convert_png_to_icns $HOME/Documents/Images/Icons/Unity\ Hub.png $HOME/Documents/Images/Icons/Unity\ Hub
  fi

  cp $HOME/Documents/Images/Icons/Unity\ Hub.icns /Applications/Unity\ Hub.app/Contents/Resources/Unity\ Hub.icns
}
