#!/bin/bash

function overwrite_unityhub_icon() {
  convert_png_to_icns $HOME/iCloud\ Drive/Documents/Images/アイコン/Unity\ Hub.png $HOME/iCloud\ Drive/Documents/Images/アイコン/Unity\ Hub && mv $HOME/iCloud\ Drive/Documents/Images/アイコン/Unity\ Hub.icns /Applications/Unity\ Hub.app/Contents/Resources/
}
